variable "db_name" {}
variable "identifier" {}
variable "engine" {}
variable "engine_ver" {}
variable "db_username" {}
variable "db_password" {}
variable "instance_class" {}
variable "allocated_storage" {}
variable "apply_immediately" {}
variable "skip_final_snapshot" {}
variable "publicly_accessible" {}
variable "db_subnet_group_name" {}
variable "subnet_ids" {}
variable "vpc_security_group_ids" {}