variable "alb_name" {}
variable "alb_type" {}
variable "alb_subnets" {}
variable "alb_sgs" {}
variable "enable_https_listener" {}
variable "https_listener_tag" {}
variable "https_listener_port" {}
variable "https_listener_protocol" {}
variable "https_ssl_policy" {}
variable "https_certificate_arn" {}
variable "https_listener_action_type" {}
variable "https_target_group_arn" {}
variable "enable_http_listener" {}
variable "http_listener_port" {}
variable "http_listener_protocol" {}
variable "http_listener_action_type" {}
variable "http_listener_tag" {}
variable "redirect_port" {}
variable "redirect_protocol" {}
variable "redirect_status_code" {}
variable "tg_name" {}
variable "tg_port" {}
variable "tg_protocol" {}
variable "tg_targetype" {}
variable "vpc_id" {}